### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by AndrzejAugustynowicz** [szepeviktor/zdkimfilter#2]
Hi,

There is an issue in zdkimfilter.c code. When running on my machine I get Segmentation fault error. The reason is strdup function with NULL argument. Bellow patch that fixes the issue.

``` patch
diff -Nur old/src/zdkimfilter.c new/src/zdkimfilter.c
--- old/src/zdkimfilter.c       2016-03-16 22:38:54.760142821 +0100
+++ new/src/zdkimfilter.c       2016-03-16 23:29:41.851456220 +0100
@@ -772,7 +772,7 @@

                                        choice[i].key = parm->dyn.key;
                                        choice[i].selector = parm->dyn.selector;
-                                       if ((choice[i].domain = strdup(parm->dyn.domain)) == NULL)
+                                       if (parm->dyn.domain && (choice[i].domain = strdup(parm->dyn.domain)) == NULL)
                                                rtc = parm->dyn.rtc = -1;

                                        parm->dyn.key = NULL;
```

**Comment by szepeviktor** [comment]
@alevesely Could you confirm it?

**Comment by alevesely** [comment]
Andrzej's fix prevents segmentation fault, but doesn't catch the problem.

The problem is that neither the authenticated sender name nor the "default_domain" item of zdkimfilter.conf contain a domain name that could be used for signing.

I'd fix it in the called function (see`svn diff -r 140:141 http://www.tana.it/svn/zdkimfilter/trunk/src/zdkimfilter.c`):

``` diff
--- zdkimfilter.c   (revision 140)
+++ zdkimfilter.c   (revision 141)
@@ -689,8 +689,16 @@
    if (type == '*' &&
        (domain = strchr(parm->dyn.info.authsender, '@')) != NULL)
            ++domain;
-   else
-       domain = parm->z.default_domain; // is that how local domains work?
+   else  // is that how local domains work?
+       if ((domain = parm->z.default_domain) == NULL)
+       {
+           fl_report(type == '*'? LOG_CRIT: LOG_ERR,
+               "id=%s: no '%c' domain name for %s: configure default_domain",
+               parm->dyn.info.id,
+               type,
+               parm->dyn.info.authsender);
+           rc = -1;
+       }

    if (domain &&
        (rc = read_key(parm, domain)) == 0)
```

Non-zero rc should stop processing `key_choice_header` and then log a "not signing for ...".

If the domain is not in the authenticated sender token and no `default_domain` is configured, it is an error to use '*' or '-' to refer to it.  I'm not clear if Courier can be configured so as to have both "name@domain" and "nameonly" kind of tokens.  Perhaps the severity should be set otherwise?

I have not tested this patch.  @AndrzejAugustynowicz Would you check if it works bot with and without configuring `default_domain`, please?

Thank you for reporting.

**Comment by AndrzejAugustynowicz** [comment]
> The problem is that neither the authenticated sender name nor the "default_domain" item of 
> zdkimfilter.conf contain a domain name that could be used for signing.

I don't think it is the issue here.

My zdkimfilter.conf configuration:
all_mode = Y
verbose = 3
selector = zumb
key_choice_header = from -

I don't have default_domain set. My domain is taken from the From header.

Your patch doesn't work for me. The message is not signed:

```
Mar 17 21:35:54 hostname dkimsign[19834]: zdkimfilter[19835]:id=dkimsign: no '-' domain name for postmaster: configure default_domain
Mar 17 21:35:54 hostname dkimsign[19834]: zdkimfilter[19835]:id=dkimsign: not signing for postmaster: no domain
Mar 17 21:35:54 hostname dkimsign[19834]: zdkimfilter exited 0, rtc=1
```

Bellow output from dkimsign command (cat a | dkimsign --filter 2>&1):
- with your patch: (works only with default_domain set)

```
rd=23, next= 0
rd=72, next=23
rd= 1, next=95
rd=24, next= 0
rd=50, next=24
rd= 1, next=74
From: my email...
To: XXX
Subject: aaa

sdasdasd
rd=35, next= 0
rd= 0, next= 0
dkimsign[19834]: received signal Child exited
```
- with my patch: (works both with/without default_domain set)

```
DKIM-Signature: v=1; a=rsa-sha256; c=simple/simple; d=domain.eu;
        s=zumb; t=1458247436;
        bh=sec8QQsoHNl00pcXpayQ+meUQdxBfgImywaq0OO9N8I=; l=10;
        h=From:To:Subject;
        b=gmNAkP0ExNMC94RruU9MlsyVEzVSwk6Tn7IUiOFeth+omY46yxYQvHb+qqf7HeO54
         dcAvoq4ZkN7yiLjtsIaoiUbaD1ecWBjUeeGe5FLPCc5nlSa6Rlx6cZohW7qEu95lUv
         eOz1oP/inqSpK4pqpJOd0utkDEj5+Ecpla8lIneOSbXfnl9uANgi6j8QuFli4R1MZy
         Biq2QipTqx2Ilcd79+Q4kibuWiMiOqoRSy6Xi2SKMDVE52eAJQ0GfrcMH4/KccFvtV
         pmMmGqkwigoetattWiOisPnQ9LrrMNkS9RslbYqcJtqr+0CcOUOldJr4IOHxQrsirI
         De34BS5KUJCgw==
From: my email ...
To: XXX
Subject: aaa

sdasdasd
rd=25, next= 0
rd= 0, next= 0
dkimsign[20481]: received signal Child exited
```

**Comment by alevesely** [comment]
The program doesn't crash --a major annoyance for a mail filter.  In that sense the patch worked, and logged as expected.  It should sign without `default_domain` if you don't refer to it; that is, if you remove that minus ('-') from `key_choice_header`.

It is correct to point out that the filter could have signed even in the face of a configuration problem, as long as a domain can be derived from `From:`.  But then we're in for a surprise if `From:` is missing or brings no domain.  Isn't it more irritating if a malfunction happens after possibly several months?

**Comment by AndrzejAugustynowicz** [comment]
I have removed minus from `key_choice_header` option and it works as expected. Thanks for your help.
