### ISSUE TITLE
Altered From header while calculating the signature

### ISSUE THREAD

**Issue by szepeviktor** [szepeviktor/zdkimfilter#3]
@alevesely When calculating the signature zdkim alters the From and Reply-to headers. Could it be that the utf8 quoted printable encoding is misunderstood?
**Somehow these changes do not get into the sent message** but surely into the signature (because adding back these linebreaks fixes DKIM), or Courier removes the line breaks later on.

```bash
dkimsign --domain munkaugyiforum.hu --sender info@munkaugyiforum.hu --filter < received-unsigned > received-resigned
```

`$ diff received-unsigned received-resigned`

```diff
0a1,8
> DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/simple; d=munkaugyiforum.hu;
>      s=muf1208; t=1480704719;
>      bh=/XGVVl/3+m8oFIq2H1Y822Zj8KkuYaLXzGOJwgfpmRU=; l=19;
>      h=Date:To:From:Subject;
>      b=DuREif53nqi9oinNzeaBxqeE58LTIrKrUznzdAkINSabsMLqyu7ewIuSUrATpi44a
>       9hxVjpFznKu9HKNeA7HLe/9aHcgLRiJ/zBDEaBIzGN6jrDhXWKbZjTnJjyMNTLBzQ3
>       PDcgJNGSvQlz6xmM2M9zA5Wn21/icL6/94Yszpf8=
> Authentication-Results: munkaugyiforum.hu; auth=pass (details omitted)
7c15,16
< From: =?utf-8?Q?Munka=C3=BCgyi_F=C3=B3rum_Kft?= <hirlevel@munkaugyiforum.hu>
---
> From:
>  =?utf-8?Q?Munka=C3=BCgyi_F=C3=B3rum_Kft?= <hirlevel@munkaugyiforum.hu>
```

**Comment by szepeviktor** [comment]
With plain From `From: Fixed from <hirlevel@munkaugyiforum.hu>` there is no linebreak inserted.

**Comment by szepeviktor** [comment]
In the `opendkim-testmsg -K` temp files there is a space in the relaxed headers:
`from: =?utf-8?....`

I've tried also compiling it with libopendkim11 v2.11.0~alpha-8, it fails.

**Comment by szepeviktor** [comment]
This is my z= header
And **yes**, From: is altered: `From:=0D=0A=20=20=3D?utf-8?....`

```email
z=Date:=20Sat,=203=20Dec=202016=2020:14:48=20+0100|To:=20"v@szepe.n
	 et"=20<v@szepe.net>|From:=0D=0A=20=20=3D?utf-8?Q?Munka=3DC3=3DBCgy
	 i_F=3DC3=3DB3rum_Kft?=3D=20<hirlevel@munkaugyiforum.hu>|Reply-to:=
	 0D=0A=20=20=3D?utf-8?Q?Munka=3DC3=3DBCgyi_F=3DC3=3DB3rum_Kft?=3D=2
	 0<hirlevel@munkaugyiforum.hu>|Subject:=20=3D?utf-8?Q?[Preview]_MKV
	 K_OK_-_a_2016._=3DC3=3DA9vi_kreditpontos_tov=3DC3=3DA1bbk?=3D=0D=0
	 A=20=3D?utf-8?Q?=3DC3=3DA9pz=3DC3=3DA9sekr=3DC5=3D91l_sz=3DC3=3DB3
	 l=3DC3=3DB3_t=3DC3=3DA1j=3DC3=3DA9koztat?=3D=0D=0A=20=3D?utf-8?Q?=
	 3DC3=3DB3_=3DC3=3DADr=3DC3=3DA1sunk?=3D|List-Unsubscribe:=20<http:
	 //hirlevel.munkaugyiforum.hu/u.php?p=3D1c3/rs/ru/s3/1b8/rs>;
```

**Comment by alevesely** [comment]
> From: is altered: From:=0D=0A=20=20=3D?utf-8?....

That kind of rewriting was briefly discussed on [courier-users](http://www.mail-archive.com/courier-users@lists.sourceforge.net/msg37498.html). Version 1.5 of zdkimfilter fixed the related signature break by wrapping before signing. Since z= tag fields are copiend at time of signing, in this case the order is correct. That is, From: was altered before signing.  BTW, To:, Reply-To:, and Cc: undergo the same treatment.
OpenDKIM [bug #226](https://sourceforge.net/p/opendkim/bugs/226/) is related to this.  If the library has that bug, signatures of wrapped fields are created broken.

**Comment by szepeviktor** [comment]
Thank you.
It seems it is a solution but most MTAs - e.g. Postfix - normalizes headers and turns
```
From:
  =?utf-8?Q?Munka=C3=BCgyi_F=C3=B3rum_Kft?= <hirlevel@munkaugyiforum.hu>
```
into
```
From: =?utf-8?Q?Munka=C3=BCgyi_F=C3=B3rum_Kft?= <hirlevel@munkaugyiforum.hu>
```
or into
```
From: =?iso-8859-1?q?Munka=FCgyi_F=F3rum?= Kft <hirlevel@munkaugyiforum.hu>
```

I've just recompiled zdkimfilter with **libopendkim 2.11.0~alpha-8** and hurray! it removes the leading spaces: (content of `opendkim-testmsg -K` temp file)
```
from:=?utf-8?....
```

And the proof: https://www.mail-tester.com/web-mzbam
